import { v4 as uuidv4 } from 'uuid';

const FoodList = [
{name: "Goat Cheese Raviolis",
 price: 12,
 course: "first",
 ingredients: "Goat Cheese and garlic chice, tomato and shitake mushroom pesto",
 url:"",
 id: uuidv4(), 
},
{name: "Chicken Pot-Stickers",
 price: 12,
 course: "first",
 ingredients: "Ginger-Soy vinaigrette and English cucmber salad",
 url:"",
 id: uuidv4(), 
},
{name: "Pepsi Shrimp",
 price: 14,
 course: "first",
 ingredients: "Pepsi-Cola battered shrimp, cucumber and red pepper",
 url:"",
 id: uuidv4(), 
},
{name: "Fried Baby Calamari",
 price: 14,
 course: "first",
 ingredients: "Sweet chili sauce and cilantro oil, fried wonton tortilla",
 url:"",
 id: uuidv4(), 
},
{name: "Crab Cake",
 price: 16,
 course: "first",
 ingredients: "Baby arugula, daikon radish, lemon aioli",
 url:"",
 id: uuidv4(), 
},
{name: "Spicy Tuna Tartar",
 price: 16,
 course: "first",
 ingredients: "Ahi Tuna, Mango salsa, Quail Egg and Spicy lemon-soy",
 url:"",
 id: uuidv4(), 
},
{name: "Seafood Steamer",
 price: 18,
 course: "first",
 ingredients: "Steamed sea scallop, shrimp, mussels, baby clam, calamari, garlic butter",
 url:"",
 id: uuidv4(), 
},
{name: "Baked Japanese Eggplant",
 price: 10,
 course: "first",
 ingredients: "Roasted tomato with fresh basil and mozzarella",
 url:"",
 id: uuidv4(), 
},
{name: "Soup of the Day",
 price: 4,
 course: "first",
 ingredients: "Changes everyday",
 url:"",
 id: uuidv4(), 
}
]
export default FoodList